spring:
  column_map.learnerfamoffroll.learnerfamtype:
    type: modify
    description: Update codes for 2026 return
    value:
      &learner-fam-type
      category:
        - code: "NLM"
        - code: "EMH"
        - code: "MMH"
      canbeblank: yes
  column_map.learnerfamonroll.learnerfamtype:
    type: modify
    description: Update codes for 2026 return
    value:
      *learner-fam-type
  column_map.learnerfamoffroll.learnerfamcode:
    type: modify
    description: Update codes for 2026 return
    value:
      &learner-fam-code
      category:
      - code: "01"
      - code: "02"
      - code: "03"
      - code: "04"
      - code: "05"      
      - code: "22"
      canbeblank: yes

summer:
  column_map.learnerfamoffroll.learnerfamtype:
    type: modify
    description: Update codes for 2026 return
    value:
      *learner-fam-type
  column_map.learnerfamonroll.learnerfamtype:
    type: modify
    description: Update codes for 2026 return
    value:
      *learner-fam-type
  column_map.learnerfamoffroll.learnerfamcode:
    type: modify
    description: Update codes for 2026 return
    value:
      *learner-fam-code
