name: base-build
permissions:
  contents: read
  actions: read
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
    secrets:
      DOCKERHUB_URL:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true
      PRIVATE_REPO_TOKEN:
        required: true

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_URL }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ secrets.DOCKERHUB_URL }}:${{ inputs.tag }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            PRIVATE_REPO_TOKEN=${{ secrets.PRIVATE_REPO_TOKEN }}
