# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Publish latest LA Docker image
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_registry:
    uses: ./.github/workflows/base_build.yml
    with:
      tag: "latest"
      dockerfile: "./Dockerfile_LA"
    secrets:
      DOCKERHUB_URL: ${{ secrets.DOCKERHUB_URL }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      PRIVATE_REPO_TOKEN: ${{ secrets.LIIA_TOOLS_PIPELINE_CONFIG_PAT }}
